/*    //锌子弹壳
    event.create("rainbow:zn_casings","basic")
    //子弹头
    event.create("rainbow:bullet_shaped","basic")
    //锌子弹壳
    event.create("rainbow:zn_shaped","basic")
    //复合火药
    event.create("rainbow:composite_gunpowder","basic")
    //霰弹
    event.create("rainbow:shrapnel","basic")
    //弹头模具
    event.create("rainbow:shaped_mode","basic")
    //蛋壳模具
    event.create("rainbow:casings_mode","basic")
    //手枪蓝图
    event.create("rainbow:pistol_blue","basic")
    //步枪蓝图
    event.create("rainbow:rifle_blue","basic")
    //冲锋枪蓝图
    event.create("rainbow:submachine_blue","basic")
    //狙击枪蓝图
    event.create("rainbow:sniper_blue","basic")
    //霰弹枪
    event.create("rainbow:shotgun","basic")
    //重武器蓝图
    event.create("rainbow:heavy","basic")
    //机枪蓝图
    event.create("rainbow:mechine","basic")
    //弹夹蓝图
    event.create("rainbow:magazine","basic")
    //瞄具蓝图
    event.create("rainbow:sight","basic")
    //枪口蓝图
    event.create("rainbow:muzzle","basic")
    //枪托组件
    event.create("rainbow:buttstock","basic")
    //握把组件
    event.create("rainbow:grip","basic")
        //子弹壳
    event.create("rainbow:bullet_casings","basic")
    */