onCull = true
MaxEntityEntities = 256
qualityModes = "NORMAL"
RenderWeather = "NORMAL"
FastItemRender = false
RenderDisplayItem = false
blackListedEntities = []
whiteListedEntities = []
isAlwaysShowItemCount = true
startTime = 77.828
chatFix = false
onGui = true
GuiRXTX = false
GuiFPS = true
GuiCPU = false
GuiGPU = false
GuiRAM = false
GuiEntityCount = false
GuiPlayerPos = false
GuiServer = false
GuiCameraTarget = false
Mood = true
Particle = true
BlockBreakParticleMode = "NORMAL"
MaxParticleDistance = 128
WhiteListedParticle = []
BlackListedParticle = []
FPSMonitor = true
GuiEasyRamMode = false
GuiDisplayRamUsage = false
GuiX = 0
GuiY = 0
EntityRender = true
UseAui = false
DeBug = false
TextBackground = false
TextureAnimatedSprites = true
SoundDevicesMonitor = false
SetParticleMaxAge = false
ParticleMaxAge = 4
GuiViewMode = "NULL"
EntityCullFov = 360
MinDistance = 6
EntityDistance = 128
TickPerformance = false
